project:
  type: website

website:
  title: "IS428-G2-Group 4"
  navbar:
    left:
      - href: index.qmd
        text: Project Overview
      - href: methodology.qmd
        text: Methodology
      - href: results-analysis.qmd
        text: Results & Analysis
      - href: lessons-learnt.qmd
        text: Lessons Learnt
      - href: about-us.qmd
        text: About Us

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true

editor: visual